pipeline {
    agent any

    environment {
        VENV = "venv"
        PYTHON = "python"   // use system python in PATH
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: 'github-https', url: 'https://github.com/DiyaDoyle/CICD.git'
            }
        }

        stage('Setup Virtual Environment') {
            steps {
                dir('Pipelining_pythonApp') {
                    bat "${env.PYTHON} -m venv ${env.VENV}"
                    bat ".\\${env.VENV}\\Scripts\\python.exe -m pip install --upgrade pip"
                    bat ".\\${env.VENV}\\Scripts\\pip install -r requirements.txt"
                }
            }
        }

        stage('Run Flask App') {
            steps {
                dir('Pipelining_pythonApp') {
                    bat ".\\${env.VENV}\\Scripts\\python.exe app.py"
                }
            }
        }
    }
}
